[package]
name = "my-powdr-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-runtime = { path = "../../powdr_branch/riscv-runtime", features = [
  "std",
  "getrandom",
] }

[workspace]
